:tablevis-version: 0.5.0

= Table visualisation library

Table visualisation library (tablevis) allows creating (custom DSL) and lay outing the complicated tables.
It's design aims to be universal library for drawing tables on any canvas (e.g. simple text, screen, html).

Currently, it has implemented printer for box drawing characters or simple Ascii Characters.

Below you can find some examples of what is possible using this library.

.Table 1
----
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                Header                ┃
┡━━━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━┩
│ Row 1 Cell 1     │      Row 1 Cell 2 │
├──────────────────┼───────────────────┤
│ Row 2 Cell 1     │      Row 2 Cell 2 │
┢━━━━━━━━━━━━━━━━━━┷━━━┳━━━━━━━━━━━━━━━┪
┃        Footer        ┃   page 1/1    ┃
┗━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━━━━━━┛
----


.Table 2
----
┏━━━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃ Col 1    ┃ Col 2 ┃ Col 3 ┃
┡━━━━━━━━━━╇━━━━━━━┻━━━━━━━┩
│ 12       │ 12345678      │
├──────────┼───────────────┤
│ 12345678 │ 32            │
└──────────┴───────────────┘
----

.Table 3
----
+------------------+------------------+
|     Header 1     |     Header 2     |
+------------------+------------------+
|                 Row                 |
+-------------------------------------+
----


== How to start

Add dependency to tablevis library in your build file:

[source,groovy,subs="attributes+"]
.Gradle
----
dependencies {
    implementation("net.igsoft:tablevis:{tablevis-version}")
}
----

[source,xml,subs="attributes+"]
.Maven
----
<dependency>
    <groupId>net.igsoft</groupId>
    <artifactId>tablevis</artifactId>
    <version>{tablevis-version}</version>
</dependency>
----


== I can not see box drawing characters in IDE. What to do?

To see box drawing characters in IDE you need to have Unicode enabled console. It is not the default in Windows, so you will have to enable it manually.




sposób uzyskania UTF-8 w konsoli Eclipse: -Dfile.encoding=UTF-8 + czcionka
http://paranoid-engineering.blogspot.com/2008/05/getting-unicode-output-in-eclipse.html


== Concept and simple usage

This library is meant to provide generic algorithm for laying out tables. It has implemented printer for text tables, but with simple changes it should be possible to extend it for printing e.g. on image.

First step while creating table is its definition using Kotlin custom DSL. Let's have a look at simplest table.


[source, kotlin]
.TableExample.kt
----
ifndef::env-github[]
include::src/example/kotlin/net/igsoft/tablevis/example/TableExample.kt[tags=simplest_table]
endif::[]

ifdef::env-github[]
    val printer = TextTablePrinter()

    val table = TableBuilder(BoxTextStyleSet()) {
        row {}
    }.build()

    println(printer.print(table))
endif::[]
----

.Result
----
┌──┐
│  │
└──┘
----

Table is defined using TableBuilder() which gets as an argument StyleSet. StyleSet defines different styles e.g. for header, for footer or for common rows. StyleSet is necessary also for defining common properties for Styles. For example border crossing characters are defined in StyleSet. Think about it - it is not that simple - in case of box drawing characters you have a lot of different combinations for crossing lines, depending on lines used for drawing boxes. For example if you cross vertical pipe ('│') with horizontal pipe ('─') you should get corner character either '┌', '┐', '└' or '┘'. If you take into consideration that lines can have a different styles, then the number of combinations is overwhelming. But you do not think about it - it is defined in StyleSet.

Let's create now something more complicated.

[source, kotlin]
.TableExample.kt
----
ifndef::env-github[]
include::src/example/kotlin/net/igsoft/tablevis/example/TableExample.kt[tags=complicated_table]
endif::[]

ifdef::env-github[]

endif::[]
----

.Result
----
┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Consecutive number ┃ Month name ┃
┡━━━┯━━━━━━━━━━━━━━━━┻━━━━━━━━━━━━┩
│ 1 │ January                     │
├───┼─────────────────────────────┤
│ 2 │ February                    │
└───┴─────────────────────────────┘
----

Please notice that style set which is passed to the builder is exposed inside as a property 'styleSet'. We have used one of the styles defined inside style set - header - to define style of the first row.

Looks nice... but... Yes, in tables you would expect the first column to be aligned and to have same width. But this library do not create any assumptions about table layout at the start. So standard layout of table is based on best size of cells. "Best" in this case means fitting the whole text in it.

Every cell in the table has pre-defined two identifiers: one for column number and one for row number, so that first column in first row has pre-defined following identifiers: 'col-1' and 'row-1'. Now we want to make first column to be same size for all rows.

Let's try to make all cells in column 1 to have same, minimal possible size. To do that we have to instruct layout engine that for 'col-1' identifiers the size of columns should be same. For brevity, I am just adding missing piece of code below last row definition:

[source, kotlin]
----
// ....... 8< .......
row {
    cell {
        text = "2"
    }
    cell {
        text = "February"
    }
}

forId("col-1").setMinimalWidth()
// ....... >8 .......
----

.Result
----
┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Consecutive number ┃ Month name ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ 1                  │ January    │
├────────────────────┼────────────┤
│ 2                  │ February   │
└────────────────────┴────────────┘
----

In similar way we can define identifiers on any cell in the table. Then we can apply modifications on that cells as a whole group. We define identifiers in the cell using "id(...)" function call. Identifier can be any type e.g. String or Int.

[source, kotlin]
----
// ....... 8< .......
cell {
    id("first column", 42)
    text = "2"
}
// ....... >8 .......
----

Now the result looks a bit better - at least the size of the first column is same for all rows. But it still seems to big for the content.

Let's try to make first column narrower. We can do it by applying different transformation on first column:

[source, kotlin]
----
// ....... 8< .......
forId("col-1").setWidth(11)
// ....... >8 .......
----

.Result
----
┏━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Consecutive ┃ Month name ┃
┃ number      ┃            ┃
┡━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ 1           │ January    │
├─────────────┼────────────┤
│ 2           │ February   │
└─────────────┴────────────┘
----

Please notice how the text in first column was automatically split in such a way that it fits into the cell.

Texts in the cells are automatically split into rows based on some simple rules:
1) Tabulators are replaced with spaces.
2) Layout engine tries to preserve natural flow of the text, so new lines are kept as much as possible.
3) Layout engine tries to split text by whitespace if it is possible
4) If it is not possible layout engine splits text in the middle adding dash character at splitting point.

Now let's center first column and set its width to 6. Additionally, let's make the whole table wider. We can also add some numbers so that we can sum them and add to summary row. To keep correct layout of the table we will have to change widths for specific cells in rows, not for all of them based on column number.

Please look at the below example:

[source, kotlin]
.TableExample.kt
----
ifndef::env-github[]
include::src/example/kotlin/net/igsoft/tablevis/example/TableExample.kt[tags=financial_table]
endif::[]

ifdef::env-github[]

endif::[]
----

.Result
----
┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Conse- ┃ Month name                       ┃    Profit    ┃
┃ cutive ┃                                  ┃              ┃
┃ number ┃                                  ┃              ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│   1    │ January                          │   12 000 $   │
├────────┼──────────────────────────────────┼──────────────┤
│   2    │ February                         │   40 000 $   │
├────────┼──────────────────────────────────┼──────────────┤
│   3    │ March                            │   29 000 $   │
├────────┼──────────────────────────────────┼──────────────┤
│   4    │ April                            │   18 500 $   │
├────────┼──────────────────────────────────┼──────────────┤
│   5    │ May                              │   41 300 $   │
├────────┼──────────────────────────────────┼──────────────┤
│   6    │ June                             │   21 650 $   │
├────────┼──────────────────────────────────┼──────────────┤
│   7    │ July                             │   30 150 $   │
├────────┼──────────────────────────────────┼──────────────┤
│   8    │ August                           │   29 999 $   │
├────────┼──────────────────────────────────┼──────────────┤
│   9    │ September                        │   24 700 $   │
├────────┼──────────────────────────────────┼──────────────┤
│   10   │ October                          │   22 890 $   │
├────────┼──────────────────────────────────┼──────────────┤
│   11   │ November                         │   51 135 $   │
├────────┼──────────────────────────────────┼──────────────┤
│   12   │ December                         │   49 134 $   │
┢━━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╈━━━━━━━━━━━━━━┪
┃ Sum                                       ┃  370 458 $   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━━━━━┛
----

In this case we have used property 'width' on the table builder. The same property can be used on rows and on cells. There are also different properties connected with style, which are inherited by child elements. For example if you enforce centering on table element level, that will be respected for the same style on other elements. Please notice that if you provide style for some specific row, that will effectively cancel inheritance, as it will be overwritten by new style. Let's see it on some fancy example:

[source, kotlin]
.TableExample.kt
----
ifndef::env-github[]
include::src/example/kotlin/net/igsoft/tablevis/example/TableExample.kt[tags=simple_text_table]
endif::[]

ifdef::env-github[]

endif::[]
----

.Result
----
+~==~==~==~==~==~==+==~==~==~==~==~==~+
*         Header 1 * Header 2         *
+~==~==~==~==~==~==+==~==~==~==~==~==~+
|                 Row                 |
+------------------+------------------+
|           Cell 1 | Cell 2           |
+------------------+------------------+
----

Although 'center()' is defined on top level, it is overridden on lower levels, either on row level or cell level.

There are many more options, which you can discover by looking on unit tests.

Have fun with tables!

== Properties of 'tablevis' in a glance

* Simple and intuitive way of defining tables
* Automatic text handling
* Constrained definition of tables
* Properties are inherited by children elements
