name: Tests
on:
  - push
  - workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        # https://github.com/marketplace/actions/checkout
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v2
      - name: SETUP JAVA
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build
